### PR TITLE
Upgrade Postgres v14 --> v16, plus migration for live server

### LINKED ISSUE #72: Use Postgres v16
## Issue

- Postgres 14 is 3yrs out of date at this point.
- https://github.com/hotosm/Drone-TM/blob/092316a3652733be1c1b2b5d6003889ed01d7446/docker-compose.yml#L38

## Solution

- We should update the docker-compose file to use Postgres v16 released last year.

    `image: postgis/postgis:16-3.4-alpine`

- Later this year Postgres v17 will be released and we can upgrade to that.

## Context

- Keeping on top of latest releases eases the maintenance burden / upgrade path going forward.
- This will also avoid us having to migrate v14 --> v16 if we start on v16.
- Would this affect anyone if the upgrade is done? Is there a db currently deployed anywhere?

### PR DESCRIPTION
**Pull request by spwoodcock**
Fixes #72

## Problem Solved

- Upgrading Postgres 14 --> 16, including a migration for the live server.

## Solution

- This was harder than I imagined!
- I made a separate docker-compose file to orchestrate the database upgrade.
- A script `contrib/pg-upgrade/upgrade-db.sh` can be used to automate the upgrade process.
- It checks if the upgrade has already taken place & is idempotent, so can be ran at every compose restart if required.
- See the comments in the compose file to see what each stage does.
- When redeploying to the AWS VM, it should upgrade automatically 🤞 

Let me know feedback / if anyone knows an easier way!
This is based on https://github.com/tianon/docker-postgres-upgrade

### CODE REVIEW

**Comment by mahesh-naxa** [comment]
@nischalstha9 can you look at these. I did go through it, using docker volumes & ability to upgrade db, LGTM. I am leaving you to test it out. 
thanks.

**Comment by nischalstha9** [comment]
Worked like a charm at my side! Really a clever way to perform continuous upgrade! 👍

**Review by mahesh-naxa — APPROVED** [review]

**Review by sijandh35 — APPROVED** [review]

**Comment by spwoodcock** [comment]
The proof is in the pudding as we say!

Let's see if it works on prod 😆

**Comment by spwoodcock** [comment]
Forgot to make the pg-upgrade package public before deploy!

I made it public and updated to `ghcr.io/hotosm/drone-tm/pg-upgrade:14-to-16`

Workflow https://github.com/hotosm/Drone-TM/actions/runs/10058359643 🤞

**Comment by nrjadkry** [comment]
@spwoodcock new deployments have failed.
Is this because of these changes ? 
https://github.com/hotosm/drone-tm/actions/runs/10071074857

**Comment by spwoodcock** [comment]
Thanks, we are discussing here: https://github.com/hotosm/drone-tm/pull/86

**Pull request merged**
